'use strict';
const form=document.getElementById('unlock-form'),input=document.getElementById('access-key'),status=document.getElementById('status'),button=document.getElementById('unlock');let objectUrls=[],assetMap=null,activeFrame=null;
const bytes=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
function relock(){if(activeFrame){activeFrame.remove();activeFrame=null}for(const u of objectUrls)URL.revokeObjectURL(u);objectUrls=[];if(assetMap){for(const name of Object.keys(assetMap))delete assetMap[name];assetMap=null}document.getElementById('opened').hidden=true;document.getElementById('locked').hidden=false;input.value='';input.type='password';document.getElementById('reveal').textContent='Show';status.textContent='';input.focus()}
form.addEventListener('submit',async event=>{event.preventDefault();if(!crypto.subtle){status.textContent='Open this page using HTTPS or a localhost preview.';return}button.disabled=true;status.textContent='Unlocking…';let plain;
try{const response=await fetch('payload.bin',{cache:'no-store',credentials:'omit'});if(!response.ok)throw Error('Unavailable');const envelope=await response.json();if(envelope.version!==1||envelope.kdf!=='PBKDF2-SHA256'||envelope.iterations<100000||envelope.iterations>2000000)throw Error('Invalid bundle');const salt=bytes(envelope.salt),iv=bytes(envelope.iv);if(salt.length!==32||iv.length!==12)throw Error('Invalid bundle');const passwordBytes=new TextEncoder().encode(input.value.trim());const material=await crypto.subtle.importKey('raw',passwordBytes,'PBKDF2',false,['deriveKey']);passwordBytes.fill(0);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:envelope.iterations,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['decrypt']);plain=new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv},key,bytes(envelope.ciphertext)));const bundle=JSON.parse(new TextDecoder().decode(plain));plain.fill(0);plain=null;input.value='';if(bundle.version!==1||bundle.entry!=='index.html'||!bundle.assets['index.html'])throw Error('Invalid content');assetMap=Object.create(null);
for(const[name,asset]of Object.entries(bundle.assets)){if(name==='index.html')continue;if(!/^[^/\\]+\.(html|csv|json)$/.test(name))throw Error('Invalid filename');const decoded=bytes(asset.base64);const u=URL.createObjectURL(new Blob([decoded],{type:asset.mime}));decoded.fill(0);assetMap[name]=u;objectUrls.push(u)}
const entry=bytes(bundle.assets['index.html'].base64);let html=new TextDecoder().decode(entry);entry.fill(0);if(!html.includes('<head>'))throw Error('Invalid entry');const mapJSON=JSON.stringify(assetMap).replaceAll('<','\\u003c');html=html.replace('<head>','<head><script>window.__DASHBOARD_ASSETS__='+mapJSON+';<\/script>');for(const name of Object.keys(bundle.assets))delete bundle.assets[name];activeFrame=document.createElement('iframe');activeFrame.title='Unlocked private dashboard';activeFrame.setAttribute('sandbox','allow-scripts allow-same-origin allow-downloads allow-popups allow-popups-to-escape-sandbox');activeFrame.srcdoc=html;html='';document.getElementById('frame-host').append(activeFrame);document.getElementById('locked').hidden=true;document.getElementById('opened').hidden=false;status.textContent='';
}catch(error){if(plain)plain.fill(0);relock();status.textContent='Unable to unlock. Check the access key and try again.'}finally{button.disabled=false}});
document.getElementById('lock').addEventListener('click',relock);document.getElementById('reveal').addEventListener('click',()=>{input.type=input.type==='password'?'text':'password';document.getElementById('reveal').textContent=input.type==='password'?'Show':'Hide'});window.addEventListener('pagehide',()=>{for(const u of objectUrls)URL.revokeObjectURL(u)});
